all:
	vcs -y $$XILINX/verilog/src/unisims -y $$XILINX/verilog/src/xilinxcorelib \
+incdir+$$XILINX/verilog/src +libext+.v $$XILINX/verilog/src/glbl.v \
-Mupdate -R -sverilog \
$$DV_ROOT/verif/env/MC_packet_trans_test/DDR3_model/mc_model_DDR3_wrapper.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/afifo.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/cmd_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/cmd_prbs_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/data_prbs_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/ddr3_model.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/init_mem_pattern_ctr.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/mcb_flow_control.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/mcb_traffic_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/rd_data_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/read_data_path.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/read_posted_fifo.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/sp6_data_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/tg_status.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/v6_data_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/wiredly.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/wr_data_gen.v \
$$DV_ROOT/verif/env/MC_packet_trans_test/infrastructure/write_data_path.v \
$$DV_ROOT/design/fpga/memory_controller/ecc/*.v \
$$DV_ROOT/design/fpga/memory_controller/controller/*.v \
$$DV_ROOT/design/fpga/memory_controller/phy/*.v \
$$DV_ROOT/design/fpga/memory_controller/ip_top/*.v \
$$DV_ROOT/design/fpga/memory_controller/ui/*.v \
$$DV_ROOT/design/fpga/mig_trans_intfc/pkt_trans_dp_const_input.t.v \
$$DV_ROOT/design/fpga/mig_trans_intfc/pkt_trans_dp.v

#> make_out.txt

